name: Render & Deploy Site

on:

  push:
    branches: [ main ]

  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:

      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: ~/.local/share/renv
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-

      - uses: r-lib/actions/setup-r@master

      - uses: r-lib/actions/setup-pandoc@master
      
      - name: Install extra system Dependencies
        run: sudo apt install -y libmpfr-dev

      - name: Install Dependencies
        
        run: |
          install.packages("renv")
          renv::restore()
        shell: Rscript {0}


      - name: Render Site
        run: rmarkdown::render_site(encoding = 'UTF-8')
        shell: Rscript {0}
        
      - name: Copy CNAME to docs
        run: cp $GITHUB_WORKSPACE/CNAME $GITHUB_WORKSPACE/docs/

      - name: Commit results
        run: |
          git config --global user.name ${{ secrets.USER_DEPLOY }}
          git config --global user.email ${{ secrets.USER_DEPLOY_MAIL }}
          git add .
          git commit -m "Automatic Render and Deploy"
          git push
